# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87bd5049222860ffffcd0e4682a70e4d34f0c3b87975181eb54c65e2048218cd5eeb4ab024000109d14cdb716c3f0079b02c078a81189b93836ff67adee5383d

test:
  secret_key_base: 3b30f7f80a7dcec2cae6f27d077e7c56a456af0d1005fc8f66bd644dc242842fb9beb093edf63a4c1d4ebec5280620ea688033bf4bd33e8708bd38dc83e9b590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
